### ISSUE TITLE
还是觉得如果hook解决了652000问题 这个工具基本上没啥用处了。

### ISSUE THREAD

**Issue by lozn00** [fourbrother/icodetools#2]
主要毛病就是无法知道方法参数长度 不知道到底调用的是哪个。另外最大的毛病就是过滤问题了，我弄了一个文本写入分割改进，但是 我擦qq信息大量大量了 过滤了几十个类还是不断的打印，只要稍微滚动一下ui又是疯狂打印-addfilter mqq.app.AppRuntime,com.tencent.mobileqq.pb.MessageMicro,com.tencent.mobileqq.app.message.MsgProxyUtils,com.tencent.beacon.event.b$1,com.tencent.image.QQLiveImagecom.tencent.qphone.base.util.QLog,com.tencent.mobileqq.statistics.UnifiedMonitor,com.tencent.qphone.base.util.QLog$c,com.tencent.beacon.event.g.t,oicq.wlogin_sdk.tools.b.a,cooperation.qzone.LocalMultiProcConfig.a,com.tencent.qphone.base.util.QLog$c,zod.a,com.tencent.mobileqq.statistics.UnifiedMonitor,com.tencent.mobileqq.statistics.StatisticCollector,com.tencent.mobileqq.msf.sdk.MsfSdkUtils,com.tencent.commonsdk.pool.RecyclablePool$Recyclable,com.tencent.commonsdk.pool.RecyclablePool,com.tencent.open.base.MD5Utils_method_dFromcom.tencent.open.base.MD5Utils.com.tencent.open.base.MD5Utils.a,com.tencent.beacon.e.a,com.tencent.mobileqq.utils.SecurityUtile,com.tencent.qphone.base.util.QLog$b,com.tencent.qphone.base.util.h,com.qq.taf.jce.JceInputStream,com.tencent.beacon.d.a,com.tencent.open.base.MD5Utils,com.tencent.mobileqq.app.ThreadOptimizer,oicq.wlogin_sdk.tools.b_method_aFromoicq.wlogin_sdk.tools.b,oicq.wlogin_sdk.tools.b,com.tencent.mobileqq.app.proxy.ProxyManager,com.tencent.qphone.base.util.MsfSocketInputBuffer,com.tencent.mobileqq.msf.core.c.l,com.tencent.mobileqq.msf.core.q,com.tencent.qphone.base.util.AbsSessionInputBuffer,com.tencent.commonsdk.util.LargerInteger,com.tencent.mobileqq.msf.core.p,com.tencent.mobileqq.msf.service.a,com.tencent.mobileqq.msf.core.NetConnInfoCenterImpl$a,com.tencent.mobileqq.msf.core.NetConnInfoCenterImpl_method_checkWifiSignalStrengthsFromcom.tencent.mobileqq.msf.core.NetConnInfoCenterImpl$a,com.tencent.mobileqq.pb.PBUInt32Field,com.tencent.mobileqq.pb.PBPrimitiveField,com.tencent.mobileqq.pb.CodedOutputStreamMicro,com.tencent.mobileqq.pb.CodedOutputStreamMicro,com.tencent.mobileqq.msf.core.x,com.tencent.beacon.a.b,com.tencent.mobileqq.msf.service.h,com.tencent.beacon.event.g,com.tencent.mobileqq.app.MemoryManager,com.tencent.qphone.base.util.CodecWarpper,com.tencent.qphone.base.util.BaseApplication,com.tencent.qphone.base.remote.ToServiceMsg,com.tencent.mobileqq.msf.core.NetConnInfoCenterImpl,com.tencent.mobileqq.msf.core.o,oicq.wlogin_sdk.tools.util,com.tencent.beacon.event.h,com.tencent.mobileqq.app.MemoryConfigs,com.tencent.qphone.base.remote.FromServiceMsg,com.tencent.qqlive.mediaplayer.api.TVK_PlayerVideoInfo,com.tencent.mobileqq.widget.BubbleImageView,com.tencent.image.URLDrawable,com.tencent.util.VersionUtils,com.tencent.image.URLState,com.tencent.image.QQLiveImage,com.tencent.image.QQLiveDrawable,:com.tencent.image.QQLiveImage,com.tencent.image.QQLiveImage$EventHandler,com.tencent.widget.ListView,wlv,com.tencent.image.QQLiveImage$OnLogListener,com.tencent.mobileqq.activity.aio.AIOUtils,com.tencent.mobileqq.app.memory.MemoryReporter,com.tencent.widget.AdapterView,com.tencent.mqq.shared_file_accessor.SharedPreferencesProxyManager,com.tencent.beacon.event.o,com.tencent.image.QQLiveImage$3,friendlist.SimpleOnlineFriendInfo,com.tencent.mobileqq.pb.WireFormatMicro,com.tencent.mobileqq.pb.PBUInt64Field

**Comment by lozn00** [comment]
您老可以开发一个 比较完善的 架构写的比较好的hook神器，我现在写的 不方便管理和移除hook不过 手动敲入字符串想hook哪个类就hook哪个，但是不方便ui管理 。。也不方便选择一个类进行hook,如果做成一个类似反编译工具一下搜索一个类，通过然后ui界面选择它，然后 日志界面也可以快速输入关键字过滤，这样的hook神器期待您来开发， 哈哈很想做这件事，但是我是业余的。

**Comment by 20140103** [comment]
你好！ 我参照你的blog想实现一个类似的工具，我在执行导出的jar文件时, 提示“添加日志代码到dex文件中失败，退出！:java.lang.NoClassDefFoundError: com/googlecode/dex2jar/tools/Dex2jarCmd”这个错误，请教一下是什么原因，如何解决呢？谢谢！
